### ISSUE TITLE
Integrate interactive Python console

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#12]
For sections like code project or the exercise in lessons it's necessary a Python's console or interpreter when the users can experiment and run their own pieces of code.

_It's not possible to interact with the code_
![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/b8efe2d5-a3d3-4dc1-b8a7-5afa24cff98c)

_Without the console the practical sections are pointless_
![image (3)](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/332ba2f3-8957-41a0-b59c-daf2c764c721)

**Comment by Elmerluis0129** [comment]
This one, has not been develop already, since Christian told me to not do it. Because it would take a lot of job and time. Since we can't integrate the cmd or something like that because we gotta have something that we can handle, that's why I haven't implemented that console. I just simulate one, making it looks like a real one. I will close this issue. If now we're going to start developing that part, then let me know and reopen it.

**Comment by lopezbec** [comment]
This will be added later, not critical but still need to happened eventually

**Comment by lopezbec** [comment]
Added a code in the main directory ("[command_line_UI.py](https://github.com/lopezbec/AI_Gamification_Python/blob/main/command_line_UI.py)") to be use as foundation to complete this issue

**Comment by Elmerluis0129** [comment]
I already integrated it. If needed reopen this issue. I'm going to close it!
