### ISSUE TITLE
Add Back Button to Improve Navigation in Lessons.

### ISSUE THREAD

**Issue by DLeonProyects** [lopezbec/AI_Gamification_Python#25]
The app lacks a back button. This would be a valuable addition, allowing users to review previous information before moving forward, especially when lesson exercises build on previously presented content.

There is no back button:

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/123324761/6456a1a9-d164-452f-b6de-2513c542ba68)

**Comment by Elmerluis0129** [comment]
We already finished this one. 

I was working with @DLeonProyects @DanielDD-UNPHU. He was making the logic with the bottom. For example, the size, color, position in the window. When it will appear and when not. And I was integrating all of that in the app. I already updated github's repository. That's why I'm closing this issue after this comment.
