### ISSUE TITLE
Updating Hexad Questionarie

### ISSUE THREAD

**Issue by lopezbec** [lopezbec/AI_Gamification_Python#38]
The Hexad questionnaire is currently composed of 24 questions, it needs to be reduced to just 12 questions. Specifically the 12 questions shown in this website: [https://mihexad.cs.lafayette.edu](https://www.google.com/url?q=https://mihexad.cs.lafayette.edu/&sa=D&source=calendar&usd=2&usg=AOvVaw2cnOMKYOfvWMPCvlp9HkAU).

The questions need to be in random order and to see how each question relates to each player type, please look at Table 5 on this [PDF](https://dl.acm.org/doi/pdf/10.1145/3544548.3580968).

Lastly, pls double-check that all possible answers are working since of now when you click the "Ligeramente en Desacuerdo" you are not able to click next.

**Comment by PriBaez** [comment]
@lopezbec the problem with the answer "Ligeramente en Desacuerdo" is that it is matching the text that has the label with which it is in the code and there is a difference in the word "desacuerdo", it seems that someone updates it so that the D is capitalized when I had put it in minister. I'm fixed that already. 

For future changes in the labels please or something else, the other programmers must double-check the updated version.

**Comment by PriBaez** [comment]
The questionnaire has been updated.
