### ISSUE TITLE
Create a different color for disabled buttons

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#49]
In some cases, such as the terms and conditions window, it is necessary to differentiate the enabled buttons from the disabled ones for more, and better, clarity of the actions to be carried out at that moment.

Other windows where it should be applied would be:

- Name window (where the user is required to enter their name)
- The "Next" button of the Hexad questionnaire.

![image](https://github.com/lopezbec/AI_Gamification_Python/assets/106645242/d480d34f-d2e0-45c6-8b22-13e25c44fcac)

**Comment by lopezbec** [comment]
@PriBaez  could you provide a bit more clarification for this since I am not following 100% . Could you show some images or create a rough sketch of what you are referring? 

For this particular page, I would recommend removing the "Aceptar terminos y conciciones" box and just changing the text of the button at the bottom to "Aceptar terminos y conciciones"  since if they do not want to accept they will be asked to just close the app.

**Comment by PriBaez** [comment]
@lopezbec in this case, I'm talking about the button. When the box is checked, the IsEnable property is true, allowing you to press and thereby trigger the method or behavior of the button. Once this property is configured, the problem is that the button remains the same color with check or not the box, not letting the user know that they cannot go ahead until they confirm that they accept the terms and conditions by checking it.

**Comment by lopezbec** [comment]
For this page (the one from the consentimiento) a better approach would be to just have the check box and not the additional bottom.

For the "questions pages"  the "next/submit" button should only be enabled when an answer is selected. Having a different color when this happens would be good in this case
